Process test
pax2pay/model-cde pull request #14
Opened 2022-01-19 13:18 UTC by ChriJ

## Change
Some extended tests, but mainly support for xml/text configurations.

## Rationale
Allow usage with xml card responses.

## Impact
Text version of configurations can now be used in e.g. worker-cde

## Risk
- [x] The change does not increase the risk to the system and does therefore not require any extra risk analysis.
- [ ] A separate risk analysis has been performed and is linked below.

## Rollback
- [x] Rollback is performed by reverting the merge and redeploy.
- [ ] Rollback of this change requires special actions as outlined below.

2022-02-04 13:24 UTC, simonmika requested changes

2022-02-04 13:24 UTC, simonmika commented on Proxy/Configuration/Response/index.ts
> +	}
I think this can be replaced by:
```
export const Text = ResponseText
```
Try it.

2023-01-11 09:53 UTC, lucymeachem-p2p approved these changes

2023-01-16 11:46 UTC, rajoouddin approved these changes

2023-01-16 12:05 UTC, simonmika approved these changes

2023-01-16 12:05 UTC, merged