Separating reverse configs and normal configs.
pax2pay/model-cde pull request #20
Opened 2022-01-31 09:46 UTC by ChriJ

## Change
Added new smaller type for reverse configs.

## Rationale
To not have redundant parts in reverse configs.

## Impact
Easier to write reverse configs.

## Risk
- [x] The change does not increase the risk to the system and does therefore not require any extra risk analysis.
- [ ] A separate risk analysis has been performed and is linked below.

## Rollback
- [x] Rollback is performed by reverting the merge and redeploy.
- [ ] Rollback of this change requires special actions as outlined below.

2022-01-31 11:52 UTC, lucymeachem-p2p approved these changes

2022-02-04 13:09 UTC, simonmika requested changes

2022-02-04 13:09 UTC, simonmika commented on Proxy/Configuration/index.ts
> +
Questions:

1. Could we don't just use one format and make some of the properties optional?
2. If not, I suggest naming it `ForwardConfiguration` and `ReverseConfiguration`.

2022-02-11 09:34 UTC, rajoouddin reviewed
if everyone is happy for this to go out

2022-03-01 12:46 UTC, simonmika approved these changes

2022-03-01 12:53 UTC, merged